version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      gems:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
